# Generated by Django 4.1.5 on 2023-01-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('antibiotic', models.CharField(max_length=100)),
                ('loading_dose', models.IntegerField()),
                ('maintenance_dose', models.IntegerField()),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('procalcitonin', models.CharField(max_length=100)),
                ('white_blood_cell', models.CharField(max_length=100)),
                ('neutrophil', models.CharField(max_length=100)),
                ('s_creatinine', models.CharField(max_length=100)),
                ('cratinine_clearance', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=100)),
                ('o2_saturation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CultureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField()),
                ('time_reported', models.DateTimeField()),
                ('specimen_type', models.CharField(choices=[('blood', 'blood'), ('urine', 'urine'), ('sputum', 'sputum'), ('CSF', 'CSF'), ('Wound', 'Wound'), ('Pus', 'Pus'), ('Bal', 'Bal'), ('Stool', 'Stool'), ('Mini Bal', 'Mini Bal'), ('Aseptic Fluid', 'Aseptic Fluid'), ('Pleural Fluid', 'Pleural Fluid'), ('TISSUE', 'TISSUE')], default='Select', max_length=100)),
                ('site_of_collection', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('antibiotic_sensitivity', models.CharField(choices=[('Ampicillin', 'Ampicillin'), ('Amoxicillin/Clavulanic', 'Amoxicillin/Clavulanic'), ('Gentamicin', 'Gentamicin'), ('Co-trimoxazole', 'Co-trimoxazole'), ('Ciprofloxacin', 'Ciprofloxacin'), ('Cloxacillin', 'Cloxacillin'), ('Cefixime', 'Cefixime'), ('Tetracycline', 'Tetracycline'), ('Levofloxacin', 'Levofloxacin'), ('Doxycycline', 'Doxycycline'), ('Norfloxacin', 'Norfloxacin'), ('Penicillin', 'Penicillin'), ('Erythromycin', 'Erythromycin'), ('Linezolid', 'Linezolid'), ('Vancomycin', 'Vancomycin'), ('Imipenem', 'Imipenem'), ('Moxifloxacin', 'Moxifloxacin'), ('Ceftriaxone', 'Ceftriaxone')], default='Select', max_length=100)),
                ('multi_drug_resistant', models.CharField(choices=[('MDR', 'MDR'), ('Non MDR', 'Non MDR'), ('PS(Pan sensitive)', 'PS(Pan sensitive)'), ('NA(No organism)', 'NA(No organism)')], default='Select', max_length=100)),
                ('resistance', models.CharField(choices=[('CRE( Carbapenemase resistant enterobactereciae)', 'CRE( Carbapenemase resistant enterobactereciae)'), ('ESBL(Extended spectrum beta lactamase)', 'ESBL(Extended spectrum beta lactamase)'), ('MRSA(Methicillin resistant staphylococcus aureus)', 'MRSA(Methicillin resistant staphylococcus aureus)'), ('VRE(Vancomycin resistant enterococcus)', 'VRE(Vancomycin resistant enterococcus)'), ('CRAB( Carbapenem resistant acinetobacter baumannii)', 'CRAB( Carbapenem resistant acinetobacter baumannii)'), ('Col Re( Colistin resistant)', 'Col Re( Colistin resistant)'), ('NA-None of the above', 'NA-None of the above')], default='Select', max_length=100)),
                ('impression', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FocusOfInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sepsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stewardship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
                ('review_department', models.CharField(max_length=100)),
                ('provisional_diagnosis', models.CharField(max_length=200)),
                ('final_diagnosis', models.CharField(max_length=200)),
                ('syndromic_diagnosis', models.CharField(max_length=200)),
                ('surity', models.CharField(choices=[('probable', 'probable'), ('definite', 'definite'), ('NONE', 'NONE')], default='Select', max_length=100)),
                ('cultureReport', models.BooleanField()),
                ('antibiotic_used', models.ManyToManyField(blank=True, to='stewardship.antibiotic')),
                ('clinical_signs', models.ManyToManyField(blank=True, to='stewardship.clinicalsign')),
                ('culture_report', models.ManyToManyField(blank=True, to='stewardship.culturereport')),
                ('focus_of_infection', models.ManyToManyField(blank=True, to='stewardship.focusofinfection')),
                ('sepsis', models.ManyToManyField(blank=True, to='stewardship.sepsis')),
            ],
        ),
        migrations.AddField(
            model_name='culturereport',
            name='Imaging',
            field=models.ManyToManyField(blank=True, to='stewardship.imaging'),
        ),
        migrations.AddField(
            model_name='culturereport',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stewardship.stewardship'),
        ),
        migrations.AddField(
            model_name='clinicalsign',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stewardship.stewardship'),
        ),
        migrations.AddField(
            model_name='antibiotic',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stewardship.stewardship'),
        ),
    ]
