# Generated by Django 4.1.5 on 2023-02-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stewardship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacist',
        ),
    ]
