# Generated by Django 4.1.5 on 2023-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culturereport",
            name="multi_drug_resistant",
            field=models.CharField(
                choices=[
                    ("MDR", "MDR"),
                    ("Non MDR", "Non MDR"),
                    ("PS(Pan sensitive)", "PS(Pan sensitive)"),
                    ("NA(No organism)", "NA(No organism)"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="culturereport",
            name="resistance",
            field=models.CharField(
                choices=[
                    (
                        "CRE( Carbapenemase resistant enterobactereciae)",
                        "CRE( Carbapenemase resistant enterobactereciae)",
                    ),
                    (
                        "ESBL(Extended spectrum beta lactamase)",
                        "ESBL(Extended spectrum beta lactamase)",
                    ),
                    (
                        "MRSA(Methicillin resistant staphylococcus aureus)",
                        "MRSA(Methicillin resistant staphylococcus aureus)",
                    ),
                    (
                        "VRE(Vancomycin resistant enterococcus)",
                        "VRE(Vancomycin resistant enterococcus)",
                    ),
                    (
                        "CRAB( Carbapenem resistant acinetobacter baumannii)",
                        "CRAB( Carbapenem resistant acinetobacter baumannii)",
                    ),
                    ("Col Re( Colistin resistant)", "Col Re( Colistin resistant)"),
                    ("NA-None of the above", "NA-None of the above"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="culturereport",
            name="specimen_type",
            field=models.CharField(
                choices=[
                    ("blood", "blood"),
                    ("urine", "urine"),
                    ("sputum", "sputum"),
                    ("CSF", "CSF"),
                    ("Wound", "Wound"),
                    ("Pus", "Pus"),
                    ("Bal", "Bal"),
                    ("Stool", "Stool"),
                    ("Mini Bal", "Mini Bal"),
                    ("Aseptic Fluid", "Aseptic Fluid"),
                    ("Pleural Fluid", "Pleural Fluid"),
                    ("TISSUE", "TISSUE"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patientLocation",
            field=models.CharField(
                choices=[("ICU", "ICU"), ("WARD", "WARD"), ("NONE", "NONE")],
                default="",
                max_length=100,
            ),
        ),
    ]
