# Generated by Django 4.1.5 on 2023-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusofinfection",
            name="isCatheterLinesStents",
            field=models.BooleanField(default=False),
        ),
    ]
