# Generated by Django 4.1.5 on 2023-02-20 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientform",
            old_name="cultureReport",
            new_name="isculture_report",
        ),
    ]
