# Generated by Django 4.1.5 on 2023-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stewardship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibiotic',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='clinicalsign',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='culturereport',
            name='sid',
        ),
    ]
