# Generated by Django 4.1.5 on 2023-02-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sepsis",
            name="name",
        ),
        migrations.AddField(
            model_name="sepsis",
            name="isNeutropenicSepsis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sepsis",
            name="isSepsis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sepsis",
            name="isSepticShock",
            field=models.BooleanField(default=False),
        ),
    ]
