# Generated by Django 4.1.5 on 2023-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinicalsign",
            old_name="patientId",
            new_name="patient",
        ),
        migrations.RemoveField(
            model_name="patientform",
            name="clinical_signs",
        ),
        migrations.AlterField(
            model_name="culturereport",
            name="resistance",
            field=models.CharField(
                choices=[
                    (
                        "CRE (Carbapenem resistant enterobactereciae)",
                        "CRE (Carbapenem resistant enterobactereciae)",
                    ),
                    (
                        "CRAB (Carbapenem resistant acenetobacter)",
                        "CRAB (Carbapenem resistant acenetobacter)",
                    ),
                    (
                        "ESBL (Extended spectrum Beta lactamase)",
                        "ESBL (Extended spectrum Beta lactamase)",
                    ),
                    (
                        "MRSA (Methicillin resistant Staph Aureus)",
                        "MRSA (Methicillin resistant Staph Aureus)",
                    ),
                    (
                        "VRE (Vancomycin resistant Enterococcus)",
                        "VRE (Vancomycin resistant Enterococcus)",
                    ),
                    ("Col Re( Colistin resistant)", "Col Re (colistin Resistant)"),
                    ("NA", "NA"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
