# Generated by Django 4.1.5 on 2023-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0002_rename_patientid_clinicalsign_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibiotic",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibiotic",
            name="frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibiotic",
            name="loading_dose",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibiotic",
            name="maintenance_dose",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
