# Generated by Django 4.1.5 on 2023-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stewardship', '0002_remove_antibiotic_sid_remove_clinicalsign_sid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntibioticSensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ampicillin', 'Ampicillin'), ('Amoxicillin/Clavulanic', 'Amoxicillin/Clavulanic'), ('Gentamicin', 'Gentamicin'), ('Co-trimoxazole', 'Co-trimoxazole'), ('Ciprofloxacin', 'Ciprofloxacin'), ('Cloxacillin', 'Cloxacillin'), ('Cefixime', 'Cefixime'), ('Tetracycline', 'Tetracycline'), ('Levofloxacin', 'Levofloxacin'), ('Doxycycline', 'Doxycycline'), ('Norfloxacin', 'Norfloxacin'), ('Penicillin', 'Penicillin'), ('Erythromycin', 'Erythromycin'), ('Linezolid', 'Linezolid'), ('Vancomycin', 'Vancomycin'), ('Imipenem', 'Imipenem'), ('Moxifloxacin', 'Moxifloxacin'), ('Ceftriaxone', 'Ceftriaxone')], default='Select', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='culturereport',
            name='antibiotic_sensitivity',
        ),
        migrations.AddField(
            model_name='culturereport',
            name='antibiotic_sensitivity',
            field=models.ManyToManyField(blank=True, to='stewardship.antibioticsensitivity'),
        ),
    ]
