# Generated by Django 4.1.5 on 2023-02-28 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0002_focusofinfection_iscatheterlinesstents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="focusofinfection",
            old_name="isCatheterLinesStents",
            new_name="isCatheterLinesStens",
        ),
    ]
