# Generated by Django 4.1.5 on 2023-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0002_remove_user_is_lab_remove_user_is_pharmacist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sepsis",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
