# Generated by Django 4.1.5 on 2023-03-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0002_alter_culturereport_multi_drug_resistant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientform",
            name="isAnalyzed",
            field=models.BooleanField(default=False),
        ),
    ]
