# Generated by Django 4.1.5 on 2023-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0003_alter_sepsis_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_doctor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_nurse",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_patient",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
