# Generated by Django 4.1.5 on 2023-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0003_patientform_isanalyzed"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="lastAnalysisDate",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="lastReviewDate",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
