# Generated by Django 4.1.5 on 2023-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship",
            "0003_alter_antibiotic_duration_alter_antibiotic_frequency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisform",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientform",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
