# Generated by Django 4.1.5 on 2023-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0004_patient_lastanalysisdate_patient_lastreviewdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compliance",
            old_name="isAntibiotisculture_reporticDoseChanged",
            new_name="isAntibiotisDoseChanged",
        ),
        migrations.AlterField(
            model_name="analysisform",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
