# Generated by Django 4.1.5 on 2023-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0004_remove_user_is_doctor_remove_user_is_nurse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="isAdmin",
        ),
        migrations.AddField(
            model_name="user",
            name="isStaff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
