# Generated by Django 4.1.5 on 2023-02-28 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship",
            "0004_rename_iscatheterlinesstens_focusofinfection_iscatheterlinesstents",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="antibioticsensitivity",
            old_name="name",
            new_name="antibiotic",
        ),
    ]
