# Generated by Django 4.1.5 on 2023-06-09 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0004_analysisform_draft_patientform_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisform",
            name="draft",
        ),
    ]
