# Generated by Django 4.1.5 on 2023-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship",
            "0005_rename_isantibiotisculture_reporticdosechanged_compliance_isantibiotisdosechanged_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="serum_creatinine",
            field=models.IntegerField(default=None),
        ),
    ]
