# Generated by Django 4.1.5 on 2023-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship", "0005_remove_analysisform_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admittingDoctor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="cormorbodities",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
